import { randomUUID } from "node:crypto";
import type { drizzle } from "drizzle-orm/bun-sqlite";
import * as schema from "../src/db/schema";

type DB = ReturnType<typeof drizzle<typeof schema>>;
/**
 * Create a test user
 */
export async function createUser(
  db: DB,
  overrides?: Partial<typeof schema.users.$inferInsert>,
): Promise<typeof schema.users.$inferSelect> {
  const id = overrides?.id ?? randomUUID();
  const createdAt = overrides?.createdAt ?? new Date();

  const [user] = await db
    .insert(schema.users)
    .values({ id, createdAt })
    .returning();

  if (!user) throw new Error("Failed to create user");
  return user;
}

/**
 * Create a test article
 */
export async function createArticle(
  db: DB,
  userId: string,
  overrides?: Partial<typeof schema.articles.$inferInsert>,
): Promise<typeof schema.articles.$inferSelect> {
  const id = overrides?.id ?? randomUUID();
  const url = overrides?.url ?? `https://example.com/article-${id.slice(0, 8)}`;
  const title = overrides?.title ?? null;
  const status = overrides?.status ?? "pending";
  const createdAt = overrides?.createdAt ?? new Date();

  const [article] = await db
    .insert(schema.articles)
    .values({
      id,
      userId,
      url,
      title,
      status,
      createdAt,
    })
    .returning();

  if (!article) throw new Error("Failed to create article");
  return article;
}

/**
 * Create a completed article with metadata
 */
export async function createCompletedArticle(
  db: DB,
  userId: string,
  overrides?: Partial<typeof schema.articles.$inferInsert>,
): Promise<typeof schema.articles.$inferSelect> {
  const id = overrides?.id ?? randomUUID();
  const url = overrides?.url ?? `https://example.com/article-${id.slice(0, 8)}`;
  const title = overrides?.title ?? "Test Article Title";
  const description = overrides?.description ?? "Test article description";
  const siteName = overrides?.siteName ?? "Example Site";
  const imageUrl = overrides?.imageUrl ?? "https://example.com/image.jpg";

  const [article] = await db
    .insert(schema.articles)
    .values({
      id,
      userId,
      url,
      title,
      description,
      siteName,
      imageUrl,
      status: "completed",
      processedAt: new Date(),
      createdAt: new Date(),
    })
    .returning();

  if (!article) throw new Error("Failed to create completed article");
  return article;
}

/**
 * Create a test tag
 */
export async function createTag(
  db: DB,
  userId: string,
  name: string,
  overrides?: Partial<typeof schema.tags.$inferInsert>,
): Promise<typeof schema.tags.$inferSelect> {
  const id = overrides?.id ?? randomUUID();
  const normalizedName = name.toLowerCase();

  const [tag] = await db
    .insert(schema.tags)
    .values({
      id,
      userId,
      name: normalizedName,
      autoGenerated: overrides?.autoGenerated ?? true,
    })
    .returning();

  if (!tag) throw new Error("Failed to create tag");
  return tag;
}

/**
 * Associate a tag with an article
 */
export async function addTagToArticle(
  db: DB,
  articleId: string,
  tagId: string,
): Promise<void> {
  await db.insert(schema.articleTags).values({ articleId, tagId });
}
