import { and, eq } from "drizzle-orm";
import { tags } from "../db/schema";
import type { Tag } from "../db/types";
import { db } from "../lib/db";

/**
 * Get all tags for a user
 */
export async function getUserTags(userId: string): Promise<Tag[]> {
  return await db.select().from(tags).where(eq(tags.userId, userId));
}

/**
 * Get or create a tag by name (case-insensitive)
 * Returns the tag ID
 */
export async function getOrCreateTag(
  userId: string,
  name: string,
  autoGenerated = true,
): Promise<string> {
  const normalizedName = name.toLowerCase();

  // Check if tag exists
  const [exisingTag] = await db
    .select()
    .from(tags)
    .where(and(eq(tags.userId, userId), eq(tags.name, normalizedName)))
    .limit(1);

  if (exisingTag) {
    return exisingTag.id;
  }

  // Create new tag
  const [newTag] = await db
    .insert(tags)
    .values({
      userId,
      name: normalizedName,
      autoGenerated,
    })
    .returning();

  if (!newTag) {
    throw new Error("Failed to create tag");
  }

  return newTag?.id;
}

/**
 * Delete a tag
 * Note: Cascade delete will remove all article-tag associations
 */
export async function deleteTag(tagId: string, userId: string): Promise<void> {
  await db.delete(tags).where(and(eq(tags.id, tagId), eq(tags.userId, userId)));
}
