import { eq, and } from "drizzle-orm";
import { db, tags } from "../lib/db";

export interface Tag {
  id: string;
  userId: string;
  name: string;
  autoGenerated: boolean;
  createdAt: Date;
}

/**
 * Get all tags for a user
 */
export async function getUserTags(userId: string): Promise<Tag[]> {
  return await db.select().from(tags).where(eq(tags.userId, userId));
}

/**
 * Get or create a tag by name (case-insensitive)
 * Returns the tag ID
 */
export async function getOrCreateTag(
  userId: string,
  name: string,
  autoGenerated = true
): Promise<string> {
  const normalizedName = name.toLowerCase();

  // Check if tag exists
  const existingTags = await db
    .select()
    .from(tags)
    .where(and(eq(tags.userId, userId), eq(tags.name, normalizedName)))
    .limit(1);

  if (existingTags.length > 0) {
    return existingTags[0].id;
  }

  // Create new tag
  const newTag = await db
    .insert(tags)
    .values({
      userId,
      name: normalizedName,
      autoGenerated,
    })
    .returning();

  return newTag[0].id;
}

/**
 * Delete a tag
 * Note: Cascade delete will remove all article-tag associations
 */
export async function deleteTag(tagId: string, userId: string): Promise<void> {
  await db
    .delete(tags)
    .where(and(eq(tags.id, tagId), eq(tags.userId, userId)));
}
